from pathlib import Path


MIGRATIONS = Path(__file__).resolve().parents[1] / "migrations"


def test_admin_user_migration_keeps_max_user_id_primary_key_and_adds_unique_identity() -> None:
    base_schema = (MIGRATIONS / "002_bot_state.sql").read_text()
    migration = (MIGRATIONS / "003_bot_admin_users.sql").read_text()

    assert "max_user_id TEXT PRIMARY KEY" in base_schema
    assert "ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY" in migration
    assert "CREATE UNIQUE INDEX CONCURRENTLY users_id_unique_idx ON bot_state.users (id)" in migration
    assert "ALTER COLUMN max_user_id" not in migration
    assert "REFERENCES bot_state.users(max_user_id)" in base_schema


def test_admin_grants_are_column_scoped_and_do_not_grant_the_identity_sequence() -> None:
    grants = (MIGRATIONS / "003_bot_admin_users_grants_proposal.sql").read_text()

    admin_section, runtime_section = grants.split("-- bot_admin_writer never inserts", maxsplit=1)
    assert "GRANT UPDATE (subscription_status, subscription_expires_at, plate_last_digit)" in admin_section
    assert "GRANT UPDATE (last_lookup_at, recent_lookup_at, daily_service_date, daily_lookup_count)" in admin_section
    assert "ON SEQUENCE bot_state.users_id_seq TO bot_admin_writer" not in grants
    assert "public.fuel_facts" not in admin_section
    assert "public.processed_source_messages" not in admin_section
    assert "GRANT USAGE ON SEQUENCE bot_state.users_id_seq TO bot_state_writer" in runtime_section
