-- Shared Neon schema authority: fuel-monitor.
-- Apply manually as the database owner after migrations/001_* and migrations/002_*.
-- This keeps bot_state.users(max_user_id) as the primary key; existing foreign keys remain unchanged.
-- Do not run inside a transaction: the unique indexes are intentionally concurrent.

ALTER TABLE bot_state.users
  ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN first_seen_at TIMESTAMPTZ,
  ADD COLUMN last_seen_at TIMESTAMPTZ,
  ADD COLUMN total_accepted_fuel_lookups BIGINT NOT NULL DEFAULT 0;

UPDATE bot_state.users
SET first_seen_at = COALESCE(first_seen_at, created_at, clock_timestamp()),
    last_seen_at = COALESCE(last_seen_at, updated_at, created_at, clock_timestamp())
WHERE first_seen_at IS NULL OR last_seen_at IS NULL;

ALTER TABLE bot_state.users
  ALTER COLUMN id SET NOT NULL,
  ALTER COLUMN first_seen_at SET NOT NULL,
  ALTER COLUMN first_seen_at SET DEFAULT clock_timestamp(),
  ALTER COLUMN last_seen_at SET NOT NULL,
  ALTER COLUMN last_seen_at SET DEFAULT clock_timestamp();

CREATE UNIQUE INDEX CONCURRENTLY users_id_unique_idx ON bot_state.users (id);
CREATE INDEX CONCURRENTLY users_admin_status_id_idx
  ON bot_state.users (subscription_status, id DESC);
CREATE INDEX CONCURRENTLY callback_receipts_admin_summary_idx
  ON bot_state.callback_receipts (max_user_id, status);

CREATE OR REPLACE FUNCTION bot_state.set_users_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = clock_timestamp();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_set_updated_at ON bot_state.users;
CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON bot_state.users
  FOR EACH ROW
  EXECUTE FUNCTION bot_state.set_users_updated_at();
